this.musicPool = {
	 		_0 : {
	 			second_id : 0, // the id used when actual play, default is the same as original id 
	 			removed : false, // field marked removed song 
	 			deleted : false, // field marked for deleted song 
	 			url : 'development/music/You Need Me-KENN.mp3',
	 			song_name : 'You Need Me',
	 			singer : 'KENN',
	 			album : 'You Need Me',
	 			album_cover : 'development/music/YouNeedMeCover.jpg',
	 			lyric_with_time : false,
	 			lyric : [
	 				'You Need Me - KENN',
	 				'',
	 				'君は　覚えているかい',
	 				'はじめて 出会えた時',
	 				'(Baby I need you)',
	 				'何故か　ふいに横切る',
	 				'おそれや　不安を確かめる',
	 				'',
	 				'上手く言葉じゃ君に',
	 				'伝えられないけれと',
	 				"(I'm missing you)",
	 				'誤解しないで　悲しまないで',
	 				'勇気出して　歩き出すよ',
	 				'So Feeling my heart',
	 				'',
	 				'君の名前を（呼んでいるよ)',
	 				'僕のメロディー　この歌に乗せて',
	 				'大好きだから（心つなぐ）',
	 				'この道をゆこう　永久に',
	 				'例えどんなに　苦しい時も',
	 				'もう　離れないから',
	 				'これからもずっと',
	 				'',
	 				'愛に 終わりはあるか',
	 				'はじめて 考えたよ',
	 				"(So Don't you fake me?)",
	 				'そうさ 失うことが',
	 				'怖くて 不安を抱きしめる',
	 				'',
	 				'君に　触れた瞬間（聞こえる)',
	 				'鼓動　揺らめいた瞳が',
	 				"(Don't be afraid)",
	 				'僕を見つめて　変わらぬまま',
	 				'2人で　愛を誓い合おう',
	 				'So just stay with me',
	 				'',
	 				'君への愛を（叫んでるよ）',
	 				'僕のメロディー　この声に乗せて',
	 				'大好きだから（溢れるほど）',
	 				'この道を行こう　永久に',
	 				'例えどんなに　苦しい時も',
	 				'もう　迷わないから',
	 				'これからもずっと',
	 				'',
	 				'I miss you　消えないで',
	 				'(Oh my sweet baby)',
	 				'僕が守るから',
	 				'',
	 				'そばにいるよ···',
	 				'',
	 				'君の名前を（呼んでいるよ）',
	 				'僕のメロディー　この歌に乗せて',
	 				'大好きだから（心つなぐ）',
	 				'この道をゆこう　永久に',
	 				'',
	 				'例えどんなに　苦しい時も',
	 				'もう　離さないから',
	 				'もう　迷わないから',
	 				'これからもずっと',
	 				'',
	 				"I don't wanna leave you"
	 			]
	 		},

	 		_1 : {
	 			second_id : 1, // the id used when actual play, default is the same as original id 
	 			removed : false, // field marked removed song 
	 			deleted : false, // field marked for deleted song 
	 			url : 'development/music/Anchor-Novo Amor.mp3',
	 			song_name : 'Anchor',
	 			singer : 'Novo Amor',
	 			album : 'Achor',
	 			album_cover : 'development/music/AnchorCover.jpg',
	 			lyric_with_time : false,
	 			lyric : [
	 				'Anchor - Novo Amor',
	 				'',
	 				'Took the breath from my open mouth',
	 				'Never known how it broke me down',
	 				'I went in circles somewhere else',
	 				'',
	 				'Shook the best when your love was home',
	 				'Storing up on your summer glow',
	 				'You went in search of someone else',
	 				'',
	 				"And I hear your ship is comin' in",
	 				'Your tears a sea for me to swim',
	 				"And I hear a storm is comin' in",
	 				'My dear is it all we’ve ever been?',
	 				'',
	 				'Caught the air in your woven mouth',
	 				'Leave it all i’ll be hearing how you went',
	 				'In search of someone else',
	 				'',
	 				'They taught the hand that taut the bride',
	 				'Both our eyes locked to the tide',
	 				'We went in circles somewhere else',
	 				'',
	 				"And I hear your ship is comin' in",
	 				'Your tears a sea for me to swim',
	 				"And I hear a storm is comin' in",
	 				'My dear is it all we’ve ever been?',
	 				'',
	 				'Anchor up to me, love',
	 				'Anchor up to me, love',
	 				'Anchor up to me, love',
	 				'Oh, Anchor up to me',
	 				'My love, my love, my love'
	 			]
	 		},

	 		_2 : {
	 			second_id : 2, // the id used when actual play, default is the same as original id 
	 			removed : false, // field marked removed song 
	 			deleted : false, // field marked for deleted song 
	 			url : 'development/music/M01-梶浦由記.mp3',
	 			song_name : 'M01',
	 			singer : '梶浦由記',
	 			album : '劇場版 空の境界 Vol.2「殺人考察(前)」Original Soundtrack',
	 			album_cover : 'development/music/M01Cover.jpg',
	 			lyric_with_time : false,
	 			lyric : undefined
	 		},

	 		_3 : {
	 			second_id : 3, // the id used when actual play, default is the same as original id 
	 			removed : false, // field marked removed song 
	 			deleted : false, // field marked for deleted song 
	 			url : 'development/music/Signal-TK from 凛として時雨.mp3',
	 			song_name : 'Signal',
	 			singer : 'TK from 凛として時雨',
	 			album : 'Signal',
	 			album_cover : 'development/music/SingnalCover.jpg',
	 			lyric_with_time : false,
	 			lyric : undefined
	 		},

	 		_4 : {
	 			second_id : 4, // the id used when actual play, default is the same as original id 
	 			removed : false, // field marked removed song 
	 			deleted : false, // field marked for deleted song 
	 			url : 'development/music/WAVE-kradness.mp3',
	 			song_name : 'WAVE',
	 			singer : 'kradness',
	 			album : 'KRAD VORTEX',
	 			album_cover : 'development/music/KRADVORTEXCover.jpg',
	 			lyric_with_time : true,
	 			lyric : [
	 				['00:00', 'WAVE - kradness'],
	 				'',
	 				['00:31', '間違（まちが）えて宇宙（うちゅう）終（お）わって'],
	 				['00:32', '青信号（あおしんごう）はいつも通（とお）り'],
	 				['00:35', '飛（と）んでまた止（とま）まって'],
	 				['00:37', 'また　飛（と）びそうだ'],
	 				['00:39', 'ココロコネクト'],
	 				['00:40', '古代人（こだいじん）と恋（こい）した'],
	 				['00:42', '妄想（もうそう）コレクト'],
	 				['00:44', '化石的（かせきてき）なロマンス'],
	 				['00:46', 'はぁ…夢（ゆめ）に踊（おど）るの'],
	 				'',
	 				['00:49', '月（つき）の灯（あか）りが'],
	 				['00:51', '僕（ぼく）を包（つつ）んで'],
	 				['00:53', '鳴（な）り響（ひび）く音（おと）カラダを'],
	 				['00:55', '飲（の）み込（こ）んでいく'],
	 				['00:57', 'もう恐（おそ）れることを'],
	 				['00:59', '感（かん）じないくらいの'],
	 				['01:01', '眩（まぶ）しさに'],
	 				['01:02', '今（いま）ココロを'],
	 				['01:03', '狙（ねら）われているの'],
	 				['01:05', '回（まわ）る　回（まわ）る　世界（せかい）は'],
	 				['01:08', '///W/A//VE//'],
	 				'',
	 				['01:22', '考（かんが）えてみて止（と）まって'],
	 				['01:24', '赤信号（あかしんごう）は狙（ねら）い通（とお）り'],
	 				['01:27', '逃（に）げたくて滑（すべ）って'],
	 				['01:29', 'また　逃（に）げそうだ'],
	 				['01:31', '開（ひら）けネクスト'],
	 				['01:32', '宇宙人（うちゅうじん）とＳｋｙｐｅ'],
	 				['01:34', '妄想（もうそう）セレクト'],
	 				['01:36', '電波的（でんぱてき）なロマンス'],
	 				['01:38', 'はぁ…夜（よる）に眠（ねむ）るの'],
	 				'',
	 				['01:41', '月（つき）の灯（あか）りが'],
	 				['01:43', '僕（ぼく）を包（つつ）んで'],
	 				['01:45', '鳴（な）り響（ひび）く音（おと）カラダを'],
	 				['01:47', 'また惑（まど）わせる'],
	 				['01:48', 'もう暴（あば）れることを'],
	 				['01:50', '忘（わす）れちゃうくらいの'],
	 				['01:52', '眩（まぶ）しさに'],
	 				['01:53', '今（いま）ココロを'],
	 				['01:54', '狙（ねら）われているの'],
	 				['01:56', '迫（せま）る　迫（せま）る　未来（みらい）は'],
	 				'///W/A//VE//',
	 				'',
	 				['02:00', 'はぁーん…'],
	 				['02:23', '夢（ゆめ）に踊（おど）るのー'],
	 				['02:25', '明日（あした）の声（こえ）が'],
	 				['02:27', '僕（ぼく）を誘（さそ）って'],
	 				['02:29', '鳴（な）り響（ひび）く音（おと）ミライを'],
	 				['02:31', '塗（ぬ）り替（か）えていく'],
	 				['02:33', 'もう留（とど）まることを'],
	 				['02:35', '許（ゆる）さないくらいの'],
	 				'',
	 				['02:37', '眩（まぶ）しさに'],
	 				['02:38', '今（いま）ココロを'],
	 				['02:39', '狙（ねら）われているの'],
	 				['02:41', '回（まわ）る　回（まわ）る　世界（せかい）から'],
	 				['02:44', '見（み）える　見（み）える'],
	 				['02:46', '未来（みらい）'],
	 				'',
	 				['02:48', 'らららーららーららー'],
	 				['02:49', 'らららーららーららー'],
	 				['02:55', 'らららーららーららー'],
	 				['02:57', 'らららーららーららー']
	 			]
	 		},

	 		_5 : {
	 			second_id : 5, // the id used when actual play, default is the same as original id 
	 			removed : false, // field marked removed song 
	 			deleted : false, // field marked for deleted song 
	 			url : 'development/music/夢見る三日月-近藤隆.mp3',
	 			song_name : '夢見る3日月',
	 			singer : '近藤隆',
	 			album : '夕燒けデイズ',
	 			album_cover : 'development/music/JohnCover.jpg',
	 			lyric_with_time : false,
	 			lyric : [
	 				'夢見る三日月 - 近藤隆',
	 				'',
	 				'ちょっと前をゆく人の',
	 				'背中追って 浮かんでた',
	 				'階段の踊り場で',
	 				'見失った 道しるべ',
	 				'',
	 				'なんでかな この場所を',
	 				'知った風で 忘れてた',
	 				'奥にあった 細道で',
	 				'立ち止まって 見上げたら',
	 				'',
	 				'煙を散らして',
	 				'星を渡った',
	 				'',
	 				'ひとりきりの夢の中',
	 				'君がそばにいるだけで',
	 				'声にならない想い 焦がして',
	 				'こんなに 胸が苦しくて',
	 				'だけど 僕は戻れない',
	 				'そうやって今を漂っているんだ',
	 				'',
	 				'寝息 立てる街を',
	 				'風になって すり抜ける',
	 				'勘の冴えた 野良猫が',
	 				'僕の目を見て 鳴いた',
	 				'',
	 				'誰かと話が',
	 				'できたら良いのに',
	 				'',
	 				'ひかり灯す 悪戯で',
	 				'君に何か 伝えたくて',
	 				'猫の手も借りてみようか なんて',
	 				'どうにもならない 哀しみも',
	 				'いつか 前を向けるなら',
	 				'そうやって未来は変わっていくんだ',
	 				'',
	 				'振り返る街並みは 走馬灯のように',
	 				'やり残した願いも すべて抱きしめて',
	 				'La La La...少しのお別れだね',
	 				'La La La...だから 怖がらないで',
	 				'それじゃあ お先に',
	 				'僕は眠っているよ',
	 				'',
	 				'ひとりきりの夢の中',
	 				'君の姿 見つけたら',
	 				'精一杯の笑顔で 手を握って',
	 				'ひかりが宿る 三日月の',
	 				'迎えを待つ その場所で',
	 				'いつか 僕らにも訪れるさ',
	 				'そうやって 命は続いていくんだ'
	 			]
	 		}
	 	};